### PR TITLE
Fix the tab opening next to the current tab

### PR DESCRIPTION
**Pull request by PerfectSlayer**
To solve the issue #34 
Based on the idea of @def00111 (plus I add the selection of the opened tab)
Tested of Firefox 38

### CODE REVIEW

**Comment by bpierre** [comment]
Thanks! I still have an issue, could you confirm it’s the same for you?

- Open a web page (tab 1).
- On this page, open a link in a new tab (tab 2). That will open a background tab on the right of the current one.
- Open the Google Translate tab => it will open on the right of the newly opened tab (tab 2) instead of the current tab (tab 1).

**Comment by PerfectSlayer** [comment]
Yes! I already see it but I think this is the default behavior.
The background tabs opens close to the current tab and they stack until you open it.

If you select the tab 2 before open the translation, then get back to tab 1, the tab for gTranslate will be open between tab 1 and tab 2 (as tab 2 is no more a background tab of tab 1).

I don't think you could fix this. It's the intended behavior of background tabs. Doesn't suit you?

**Comment by bpierre** [comment]
Yes sorry, I now realize this is the exact same behaviour as “open in a new tab”. Perfect then, thanks!

**Comment by PerfectSlayer** [comment]
You're welcome!

**Pull request merged**
