### PR TITLE
Add tranlate page feature

### PR DESCRIPTION
**Pull request by PerfectSlayer**
The translate page feature is only available when no selection is made on
the page.
The option will not be presented for about: pages.

### CODE REVIEW

**Comment by bpierre** [comment]
Thanks! Just two things:

- I think it should be “Translate Page” (with a capital P) to match the capitalization style of the other menu items.
- I think we should display the current setting, e.g. `auto > English` or `Czech > Dutch`, even if we can’t change it in that mode.

**Comment by PerfectSlayer** [comment]
I don't see any capital letter other than the first one in my context menu? (maybe it's English specific?)

Agreed, I will add the current setting display the indicate what the item will lead to.

**Comment by PerfectSlayer** [comment]
I just pushed the changes.
Tell me if you see anything else.

**Comment by mote0230** [comment]
Seems alright, so I merged.

**Comment by PerfectSlayer** [comment]
Fine! I hope to see the feature shipped in a next future :smile:

**Comment by bpierre** [comment]
Thanks guys! I will test it and publish a new version this evening if everything is ok.

**Comment by mote0230** [comment]
Before publishing, can you check on the dictionary branch? It should be ready to merge in the master branch, except for code style, and it includes a couple bugfixes.

**Comment by bpierre** [comment]
@mote0230 Sure!
@PerfectSlayer I added you to the collaborators :-) (please do not push directly in the master branch, so we can discuss the changes of a feature branch before merging it)

**Comment by PerfectSlayer** [comment]
@bpierre Thanks for the privilege :smile: Don't worry, I won't force push on master :innocent:

**Pull request merged**
