### PR TITLE
Jetpack rewrite

### PR DESCRIPTION
**Pull request by bpierre**
Following #21 and #23, I am rewriting the addon to use the new Addons SDK API. The plan is to publish a basic release as soon as possible, and add more features later.

To do before the merge:

- [x] Finish the language selection
- [x] Improve the parsing of the Google Translate results
- [x] Translate selections inside `<input>` and `<textarea>`
- [ ] Test it on the current stable version of Firefox

### CODE REVIEW

**Comment by Tachikoma00** [comment]
Good to see you guys are on top of it. Can't wait.

**Comment by mlang38** [comment]
:+1:  :heart:

**Comment by Nekmo** [comment]
I love this plugin. GTranslate is for me an important reason for using Firefox.

Thanks for your work!

**Comment by mdibaiee** [comment]
Thank you! :+1:

**Pull request merged**
